webtalk_init -webtalk_dir C:/Users/Reith/Documents/DLXstuff/DLX/DLX_TOP/DLX_TOP.sim/sim_1/behav/xsim/xsim.dir/tb_DLX_TOP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec  8 21:08:37 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211605713_0_0_701" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "60d1d3c5-4056-4daa-921d-68d227ad84a0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "856a2896216f439fa0a5eb8ad157c064" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "244" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3235114315 -regid "211605713_0_0_701" -xml C:/Users/Reith/Documents/DLXstuff/DLX/DLX_TOP/DLX_TOP.sim/sim_1/behav/xsim/xsim.dir/tb_DLX_TOP_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Reith/Documents/DLXstuff/DLX/DLX_TOP/DLX_TOP.sim/sim_1/behav/xsim/xsim.dir/tb_DLX_TOP_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Reith/Documents/DLXstuff/DLX/DLX_TOP/DLX_TOP.sim/sim_1/behav/xsim/xsim.dir/tb_DLX_TOP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
